const sampleListings = [
    {
      title: "Cozy Beachfront Cottage",
      description:
        "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1500,
      location: "Malibu",
      country: "United States",
    },
    {
      title: "Modern Loft in Downtown",
      description:
        "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1200,
      location: "New York City",
      country: "United States",
    },
    {
      title: "Mountain Retreat",
      description:
        "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 1000,
      location: "Aspen",
      country: "United States",
    },
    {
      title: "Historic Villa in Tuscany",
      description:
        "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 2500,
      location: "Florence",
      country: "Italy",
    },
    {
      title: "Secluded Treehouse Getaway",
      description:
        "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 800,
      location: "Portland",
      country: "United States",
    },
    {
      title: "Beachfront Paradise",
      description:
        "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 2000,
      location: "Cancun",
      country: "Mexico",
    },
    {
      title: "Rustic Cabin by the Lake",
      description:
        "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 900,
      location: "Lake Tahoe",
      country: "United States",
    },
    {
      title: "Luxury Penthouse with City Views",
      description:
        "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 3500,
      location: "Los Angeles",
      country: "United States",
    },
    {
      title: "Ski-In/Ski-Out Chalet",
      description:
        "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 3000,
      location: "Verbier",
      country: "Switzerland",
    },
    {
      title: "Safari Lodge in the Serengeti",
      description:
        "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 4000,
      location: "Serengeti National Park",
      country: "Tanzania",
    },
    {
      title: "Historic Canal House",
      description:
        "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1800,
      location: "Amsterdam",
      country: "Netherlands",
    },
    {
      title: "Private Island Retreat",
      description:
        "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bG9kZ2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 10000,
      location: "Fiji",
      country: "Fiji",
    },
    {
      title: "Charming Cottage in the Cotswolds",
      description:
        "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmVhY2glMjB2YWNhdGlvbnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1200,
      location: "Cotswolds",
      country: "United Kingdom",
    },
    {
      title: "Historic Brownstone in Boston",
      description:
        "Step back in time in this elegant historic brownstone located in the heart of Boston.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 2200,
      location: "Boston",
      country: "United States",
    },
    {
      title: "Beachfront Bungalow in Bali",
      description:
        "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1800,
      location: "Bali",
      country: "Indonesia",
    },
    {
      title: "Mountain View Cabin in Banff",
      description:
        "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 1500,
      location: "Banff",
      country: "Canada",
    },
    {
      title: "Art Deco Apartment in Miami",
      description:
        "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
      image: {
        filename: "listingimage",
        url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 1600,
      location: "Miami",
      country: "United States",
    },
    {
      title: "Tropical Villa in Phuket",
      description:
        "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 3000,
      location: "Phuket",
      country: "Thailand",
    },
    {
      title: "Historic Castle in Scotland",
      description:
        "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGJlYWNoJTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 4000,
      location: "Scottish Highlands",
      country: "United Kingdom",
    },
    {
      title: "Desert Oasis in Dubai",
      description:
        "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZHViYWl8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 5000,
      location: "Dubai",
      country: "United Arab Emirates",
    },
    {
      title: "Rustic Log Cabin in Montana",
      description:
        "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 1100,
      location: "Montana",
      country: "United States",
    },
    {
      title: "Beachfront Villa in Greece",
      description:
        "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 2500,
      location: "Mykonos",
      country: "Greece",
    },
    {
      title: "Eco-Friendly Treehouse Retreat",
      description:
        "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 750,
      location: "Costa Rica",
      country: "Costa Rica",
    },
    {
      title: "Historic Cottage in Charleston",
      description:
        "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 1600,
      location: "Charleston",
      country: "United States",
    },
    {
      title: "Modern Apartment in Tokyo",
      description:
        "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRva3lvfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 2000,
      location: "Tokyo",
      country: "Japan",
    },
    {
      title: "Lakefront Cabin in New Hampshire",
      description:
        "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1200,
      location: "New Hampshire",
      country: "United States",
    },
    {
      title: "Luxury Villa in the Maldives",
      description:
        "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 6000,
      location: "Maldives",
      country: "Maldives",
    },
    {
      title: "Ski Chalet in Aspen",
      description:
        "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGxha2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 4000,
      location: "Aspen",
      country: "United States",
    },
    {
      title: "Secluded Beach House in Costa Rica",
      description:
        "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhY2glMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1800,
      location: "Costa Rica",
      country: "Costa Rica",
    },
  ];
  module.exports = sampleListings;
  
  // module.exports = { data: sampleListings };
  
    // {
    //   title: "Cozy Cottage Retreat",
    //   des: "Escape to this charming cottage for a peaceful getaway surrounded by nature.",
    //   img: "https://example.com/cozy-cottage.jpg",
    //   price: 100,
    //   location: "Woodland Hills",
    //   country: "United States",
    // },
    // {
    //   title: "Luxurious Beachfront Villa",
    //   des: "Indulge in the ultimate beachfront experience with this stunning villa featuring breathtaking ocean views.",
    //   img: "https://example.com/beachfront-villa.jpg",
    //   price: 300,
    //   location: "Malibu",
    //   country: "United States",
    // },
    // {
    //   title: "Mountain View Cabin",
    //   des: "Experience serenity in this cozy cabin nestled in the mountains, offering spectacular views and tranquility.",
    //   img: "https://example.com/mountain-view-cabin.jpg",
    //   price: 120,
    //   location: "Aspen",
    //   country: "United States",
    // },
    // {
    //   title: "City Center Loft",
    //   des: "Live in the heart of the city with this modern loft, surrounded by vibrant nightlife and cultural attractions.",
    //   img: "https://example.com/city-center-loft.jpg",
    //   price: 200,
    //   location: "New York City",
    //   country: "United States",
    // },
    // {
    //   title: "Secluded Lakeside Cabin",
    //   des: "Unplug and unwind in this peaceful lakeside cabin, perfect for a romantic getaway or a solo retreat.",
    //   img: "https://example.com/lakeside-cabin.jpg",
    //   price: 150,
    //   location: "Lake Tahoe",
    //   country: "United States",
    // },
    // {
    //   title: "Historic European Villa",
    //   des: "Step back in time with this beautifully restored villa, showcasing historic charm and modern amenities.",
    //   img: "https://example.com/european-villa.jpg",
    //   price: 250,
    //   location: "Tuscany",
    //   country: "Italy",
    // },
    // {
    //   title: "Modern City Apartment",
    //   des: "Enjoy the urban lifestyle in this sleek and contemporary apartment located in the heart of the city.",
    //   img: "https://example.com/city-apartment.jpg",
    //   price: 180,
    //   location: "Tokyo",
    //   country: "Japan",
    // },
    // {
    //   title: "Rustic Mountain Lodge",
    //   des: "Embrace the charm of the mountains with this rustic lodge, offering a cozy retreat amidst nature's beauty.",
    //   img: "https://example.com/mountain-lodge.jpg",
    //   price: 130,
    //   location: "Banff",
    //   country: "Canada",
    // },
    // {
    //   title: "Sunny Beach Bungalow",
    //   des: "Wake up to the sound of waves in this delightful beach bungalow, perfect for a tropical escape.",
    //   img: "https://example.com/beach-bungalow.jpg",
    //   price: 180,
    //   location: "Phuket",
    //   country: "Thailand",
    // },
    // {
    //   title: "Artistic Studio Loft",
    //   des: "Experience creativity and comfort in this artistic loft, designed for those with a passion for aesthetics.",
    //   img: "https://example.com/studio-loft.jpg",
    //   price: 120,
    //   location: "Paris",
    //   country: "France",
    // },
    // {
    //   title: "Serene Countryside Retreat",
    //   des: "Unwind in this peaceful countryside retreat, surrounded by rolling hills and fresh air.",
    //   img: "https://example.com/countryside-retreat.jpg",
    //   price: 110,
    //   location: "Cotswolds",
    //   country: "United Kingdom",
    // },
    // {
    //   title: "Ocean View Penthouse",
    //   des: "Enjoy breathtaking ocean views from this luxurious penthouse with top-notch amenities.",
    //   img: "https://example.com/ocean-view-penthouse.jpg",
    //   price: 400,
    //   location: "Miami",
    //   country: "United States",
    // },
    // {
    //   title: "Elegant Lakeside Mansion",
    //   des: "Experience grandeur in this elegant lakeside mansion, perfect for special occasions and gatherings.",
    //   img: "https://example.com/lakeside-mansion.jpg",
    //   price: 500,
    //   location: "Geneva",
    //   country: "Switzerland",
    // },
    // {
    //   title: "Charming Countryside Cottage",
    //   des: "Escape the hustle and bustle in this charming cottage surrounded by scenic countryside.",
    //   img: "https://example.com/countryside-cottage.jpg",
    //   price: 90,
    //   location: "Cork",
    //   country: "Ireland",
    // },
    // {
    //   title: "Skyline View Apartment",
    //   des: "Wake up to stunning skyline views in this modern apartment situated in a prime city location.",
    //   img: "https://example.com/skyline-view-apartment.jpg",
    //   price: 220,
    //   location: "Sydney",
    //   country: "Australia",
    // },
    // {
    //   title: "Historic Townhouse",
    //   des: "Step into history with this beautifully preserved historic townhouse in the heart of the city.",
    //   img: "https://example.com/historic-townhouse.jpg",
    //   price: 180,
    //   location: "Edinburgh",
    //   country: "United Kingdom",
    // },
    // {
    //   title: "Majestic Castle Stay",
    //   des: "Live like royalty with a stay in this majestic castle, complete with opulent furnishings and sprawling grounds.",
    //   img: "https://example.com/majestic-castle.jpg",
    //   price: 800,
    //   location: "Bavaria",
    //   country: "Germany",
    // },
    // {
    //   title: "Treehouse Retreat",
    //   des: "Experience a unique stay in this cozy treehouse, surrounded by nature and wildlife.",
    //   img: "https://example.com/treehouse-retreat.jpg",
    //   price: 120,
    //   location: "Vancouver Island",
    //   country: "Canada",
    // },
    // {
    //   title: "Luxury Safari Tent",
    //   des: "Immerse yourself in the wild with a stay in this luxurious safari tent, offering comfort and adventure.",
    //   img: "https://example.com/luxury-safari-tent.jpg",
    //   price: 250,
    //   location: "Maasai Mara",
    //   country: "Kenya",
    // },
    // {
    //   title: "Riverside Cabin",
    //   des: "Relax by the river in this charming cabin, surrounded by the soothing sounds of nature.",
    //   img: "https://example.com/riverside-cabin.jpg",
    //   price: 110,
    //   location: "Blue Ridge Mountains",
    //   country: "United States",
    // },
    // {
    //   title: "Cultural District Apartment",
    //   des: "Immerse yourself in the city's cultural scene with this stylish apartment in the heart of the arts district.",
    //   img: "https://example.com/cultural-district-apartment.jpg",
    //   price: 190,
    //   location: "Barcelona",
    //   country: "Spain",
    // },
    // {
    //   title: "Cliffside Villa",
    //   des: "Perched on the cliffs, this villa offers breathtaking views of the ocean and a private, serene escape.",
    //   img: "https://example.com/cliffside-villa.jpg",
    //   price: 350,
    //   location: "Santorini",
    //   country: "Greece",
    // },
    // {
    //   title: "Mystical Forest Cabin",
    //   des: "Find enchantment in this mystical forest cabin, surrounded by ancient trees and magical ambiance.",
    //   img: "https://example.com/forest-cabin.jpg",
    //   price: 140,
    //   location: "Black Forest",
    //   country: "Germany",
    // },
    // {
    //   title: "Zen Garden Retreat",
    //   des: "Rejuvenate your senses in this peaceful retreat with a zen garden and tranquil surroundings.",
    //   img: "https://example.com/zen-garden-retreat.jpg",
    //   price: 160,
    //   location: "Kyoto",
    //   country: "Japan",
    // },
    // {
    //   title: "Beachfront Paradise",
    //   des: "Escape to paradise with this beachfront villa, where the sand and waves are just steps away.",
    //   img: "https://example.com/beachfront-paradise.jpg",
    //   price: 280,
    //   location: "Bora Bora",
    //   country: "French Polynesia",
    // },
    // {
    //   title: "Quaint Coastal Cottage",
    //   des: "Enjoy the charm of a quaint coastal cottage with stunning views and a relaxing atmosphere.",
    //   img: "https://example.com/coastal-cottage.jpg",
    //   price: 130,
    //   location: "Cornwall",
    //   country: "United Kingdom",
    // },
    // {
    //   title: "Desert Oasis Villa",
    //   des: "Experience luxury in the desert with this oasis villa, complete with a private pool and modern amenities.",
    //   img: "https://example.com/desert-oasis-villa.jpg",
    //   price: 220,
    //   location: "Scottsdale",
    //   country: "United States",
    // },
    // {
    //   title: "Historic Canal House",
    //   des: "Step into history with a stay in this beautifully preserved historic canal house in the heart of the city.",
    //   img: "https://example.com/canal-house.jpg",
    //   price: 190,
    //   location: "Amsterdam",
    //   country: "Netherlands",
    // },
    // {
    //   title: "Ski Chalet Getaway",
    //   des: "Hit the slopes and return to this cozy ski chalet, complete with a fireplace and stunning mountain views.",
    //   img: "https://example.com/ski-chalet.jpg",
    //   price: 250,
    //   location: "Whistler",
    //   country: "Canada",
    // },
    // {
    //   title: "Tropical Island Retreat",
    //   des: "Escape to a tropical paradise with this island retreat, surrounded by palm trees and crystal-clear waters.",
    //   img: "https://example.com/tropical-island-retreat.jpg",
    //   price: 320,
    //   location: "Maldives",
    //   country: "Maldives",
    // },
    // {
    //   title: "Chic Urban Townhouse",
    //   des: "Experience urban living in style with this chic townhouse, situated in a trendy neighborhood.",
    //   img: "https://example.com/urban-townhouse.jpg",
    //   price: 180,
    //   location: "Melbourne",
    //   country: "Australia",
    // },
    // {
    //   title: "Fairy Tale Cottage",
    //   des: "Live out your fairy tale dreams in this charming cottage with a storybook setting.",
    //   img: "https://example.com/fairy-tale-cottage.jpg",
    //   price: 150,
    //   location: "Cotswolds",
    //   country: "United Kingdom",
    // },
    // {
    //   title: "Mountain Hot Springs Cabin",
    //   des: "Relax in natural hot springs with a stay in this mountain cabin, surrounded by breathtaking views.",
    //   img: "https://example.com/hot-springs-cabin.jpg",
    //   price: 160,
    //   location: "Rocky Mountains",
    //   country: "United States",
    // },
    // {
    //   title: "Sky High Penthouse",
    //   des: "Live in the lap of luxury with this sky-high penthouse offering panoramic views of the city.",
    //   img: "https://example.com/sky-high-penthouse.jpg",
    //   price: 400,
    //   location: "Dubai",
    //   country: "United Arab Emirates",
    // },
    // {
    //   title: "Rural Vineyard Cottage",
    //   des: "Experience the charm of rural life with a stay in this cottage surrounded by vineyards and rolling hills.",
    //   img: "https://example.com/vineyard-cottage.jpg",
    //   price: 120,
    //   location: "Napa Valley",
    //   country: "United States",
    // },
    // {
    //   title: "Scenic Lakeside Chalet",
    //   des: "Enjoy the serenity of a scenic lakeside chalet, perfect for a relaxing and rejuvenating retreat.",
    //   img: "https://example.com/lakeside-chalet.jpg",
    //   price: 220,
    //   location: "Lake Como",
    //   country: "Italy",
    // },
    // {
    //   title: "Contemporary Desert Villa",
    //   des: "Escape to this contemporary desert villa, where modern design meets the tranquility of the arid landscape.",
    //   img: "https://example.com/desert-villa.jpg",
    //   price: 280,
    //   location: "Palm Springs",
    //   country: "United States",
    // },
    // {
    //   title: "Historic City Center Apartment",
    //   des: "Immerse yourself in history with this beautifully preserved apartment in the heart of the city's historic district.",
    //   img: "https://example.com/historic-apartment.jpg",
    //   price: 190,
    //   location: "Rome",
    //   country: "Italy",
    // },
    // {
    //   title: "Swiss Alps Chalet",
    //   des: "Experience the beauty of the Swiss Alps with a stay in this cozy chalet, perfect for winter sports enthusiasts.",
    //   img: "https://example.com/swiss-alps-chalet.jpg",
    //   price: 300,
    //   location: "Zermatt",
    //   country: "Switzerland",
    // },
    // {
    //   title: "Sustainable Eco-Lodge",
    //   des: "Stay in harmony with nature at this sustainable eco-lodge, surrounded by lush greenery and eco-friendly features.",
    //   img: "https://example.com/eco-lodge.jpg",
    //   price: 150,
    //   location: "Costa Rica",
    //   country: "Costa Rica",
    // },
    // {
    //   title: "Treetop Sanctuary",
    //   des: "Escape to a treetop sanctuary, where you can reconnect with nature high above the forest floor.",
    //   img: "https://example.com/treetop-sanctuary.jpg",
    //   price: 180,
    //   location: "Amazon Rainforest",
    //   country: "Brazil",
    // },
    // {
    //   title: "Beachside Villa",
    //   des: "Indulge in beachfront luxury with this villa offering direct access to pristine sandy shores.",
    //   img: "https://example.com/beachside-villa.jpg",
    //   price: 350,
    //   location: "Phuket",
    //   country: "Thailand",
    // },
    // {
    //   title: "Tranquil Mountain Retreat",
    //   des: "Find peace in this tranquil mountain retreat, surrounded by alpine meadows and fresh mountain air.",
    //   img: "https://example.com/mountain-retreat.jpg",
    //   price: 130,
    //   location: "Swiss Alps",
    //   country: "Switzerland",
    // },
    // {
    //   title: "Bohemian Chic Studio",
    //   des: "Embrace bohemian vibes in this chic studio, decorated with vibrant colors and artistic flair.",
    //   img: "https://example.com/bohemian-chic-studio.jpg",
    //   price: 110,
    //   location: "Bali",
    //   country: "Indonesia",
    // },
    // {
    //   title: "Colonial Style Mansion",
    //   des: "Step into the past with a stay in this colonial-style mansion, featuring vintage charm and elegant architecture.",
    //   img: "https://example.com/colonial-mansion.jpg",
    //   price: 280,
    //   location: "Charleston",
    //   country: "United States",
    // },
    // {
    //   title: "Island Paradise Cottage",
    //   des: "Escape to a secluded island paradise with this charming cottage surrounded by turquoise waters and white sands.",
    //   img: "https://example.com/island-cottage.jpg",
    //   price: 200,
    //   location: "Seychelles",
    //   country: "Seychelles",
    // },
    // {
    //   title: "Historic Scottish Castle",
    //   des: "Live like royalty in this historic Scottish castle, complete with turrets, grand halls, and picturesque grounds.",
    //   img: "https://example.com/scottish-castle.jpg",
    //   price: 600,
    //   location: "Highlands",
    //   country: "United Kingdom",
    // },
    // {
    //   title: "Safari Lodge Tent",
    //   des: "Experience the thrill of a safari with a stay in this lodge tent, where you can observe wildlife in comfort.",
    //   img: "https://example.com/safari-lodge-tent.jpg",
    //   price: 200,
    //   location: "Serengeti",
    //   country: "Tanzania",
    // },
    // {
    //   title: "Classic Beach House",
    //   des: "Enjoy classic beach vibes in this charming beach house, just steps away from the sandy shores.",
    //   img: "https://example.com/beach-house.jpg",
    //   price: 180,
    //   location: "Cape Cod",
    //   country: "United States",
    // },
    // {
    //   title: "Underwater Hotel Suite",
    //   des: "Dive into luxury with an underwater hotel suite, offering unparalleled views of marine life and the ocean.",
    //   img: "https://example.com/underwater-suite.jpg",
    //   price: 500,
    //   location: "Maldives",
    //   country: "Maldives",
    // },
    // {
    //   title: "Medieval Village Cottage",
    //   des: "Transport yourself to medieval times with a stay in this quaint cottage nestled in a historic village.",
    //   img: "https://example.com/medieval-cottage.jpg",
    //   price: 160,
    //   location: "Provence",
    //   country: "France",
    // },
    // {
    //   title: "Lakefront Log Cabin",
    //   des: "Cozy up in this charming log cabin overlooking a peaceful lake, surrounded by nature's beauty.",
    //   img: "https://example.com/lakefront-cabin.jpg",
    //   price: 140,
    //   location: "Muskoka",
    //   country: "Canada",
    // },
    // {
    //   title: "Contemporary Beachfront Condo",
    //   des: "Experience modern beachfront living in this stylish condo with panoramic views of the coastline.",
    //   img: "https://example.com/beachfront-condo.jpg",
    //   price: 250,
    //   location: "Miami",
    //   country: "United States",
    // },
    // {
    //   title: "Historic Japanese Ryokan",
    //   des: "Immerse yourself in Japanese culture with a stay in this historic ryokan, featuring tatami mat floors and a serene garden.",
    //   img: "https://example.com/japanese-ryokan.jpg",
    //   price: 180,
    //   location: "Kyoto",
    //   country: "Japan",
    // },
    // {
    //   title: "Countryside Windmill Retreat",
    //   des: "Stay in a converted windmill and enjoy the peaceful countryside surroundings with modern comforts.",
    //   img: "https://example.com/windmill-retreat.jpg",
    //   price: 160,
    //   location: "Zeeland",
    //   country: "Netherlands",
    // },
    // {
    //   title: "Urban Jungle Loft",
    //   des: "Experience the fusion of urban living and natural elements in this loft surrounded by lush greenery.",
    //   img: "https://example.com/jungle-loft.jpg",
    //   price: 200,
    //   location: "Singapore",
    //   country: "Singapore",
    // },
    // {
    //   title: "Historic Australian Homestead",
    //   des: "Step back in time with a stay in this historic Australian homestead, surrounded by vast landscapes and native flora.",
    //   img: "https://example.com/australian-homestead.jpg",
    //   price: 220,
    //   location: "Outback",
    //   country: "Australia",
    // },
    // {
    //   title: "Glamorous Hollywood Hills Mansion",
    //   des: "Live like a star in this glamorous mansion nestled in the Hollywood Hills, offering luxury and privacy.",
    //   img: "https://example.com/hollywood-hills-mansion.jpg",
    //   price: 500,
    //   location: "Los Angeles",
    //   country: "United States",
    // },
    // {
    //   title: "Mountain Safari Lodge",
    //   des: "Embark on a mountain safari adventure with a stay in this lodge, providing a comfortable base for exploration.",
    //   img: "https://example.com/mountain-safari-lodge.jpg",
    //   price: 280,
    //   location: "Atlas Mountains",
    //   country: "Morocco",
    // },
    // {
    //   title: "Seaside Cliff Retreat",
    //   des: "Perched on a seaside cliff, this retreat offers breathtaking views of the ocean and a serene escape.",
    //   img: "https://example.com/cliff-retreat.jpg",
    //   price: 300,
    //   location: "Big Sur",
    //   country: "United States",
    // },
    // {
    //   title: "Treehouse Village",
    //   des: "Experience the magic of a treehouse village, where each unique treehouse offers a different perspective of nature.",
    //   img: "https://example.com/treehouse-village.jpg",
    //   price: 150,
    //   location: "Costa Rica",
    //   country: "Costa Rica",
    // },
    // {
    //   title: "Spanish Colonial Mansion",
    //   des: "Live in opulence with a stay in this Spanish colonial mansion, featuring grand architecture and luxurious amenities.",
    //   img: "https://example.com/spanish-colonial-mansion.jpg",
    //   price: 450,
    //   location: "Granada",
    //   country: "Spain",
    // },
    // {
    //   title: "Majestic Mountain Castle",
    //   des: "Escape to a majestic mountain castle, where the towering peaks provide a stunning backdrop to your stay.",
    //   img: "https://example.com/mountain-castle.jpg",
    //   price: 600,
    //   location: "Swiss Alps",
    //   country: "Switzerland",
    // },
    // {
    //   title: "Floating Villa Retreat",
    //   des: "Experience the novelty of a floating villa retreat, surrounded by serene waters and panoramic views.",
    //   img: "https://example.com/floating-villa.jpg",
    //   price: 350,
    //   location: "Maldives",
    //   country: "Maldives",
    // },
    // {
    //   title: "African Safari Tent",
    //   des: "Immerse yourself in the wonders of an African safari with a stay in this luxurious tent, surrounded by wildlife.",
    //   img: "https://example.com/african-safari-tent.jpg",
    //   price: 300,
    //   location: "Masai Mara",
    //   country: "Kenya",
    // },
    // {
    //   title: "Alpine Lake Cabin",
    //   des: "Cozy up in this alpine lake cabin, surrounded by the beauty of snow-capped peaks and pristine waters.",
    //   img: "https://example.com/alpine-lake-cabin.jpg",
    //   price: 180,
    //   location: "Swiss Alps",
    //   country: "Switzerland",
    // },
    // {
    //   title: "Rustic Farmhouse Retreat",
    //   des: "Escape to a rustic farmhouse retreat, where the simplicity of rural life meets modern comforts.",
    //   img: "https://example.com/farmhouse-retreat.jpg",
    //   price: 120,
    //   location: "Tuscany",
    //   country: "Italy",
    // },
    // {
    //   title: "Modern Desert Villa",
    //   des: "Embrace the stark beauty of the desert with this modern villa, offering a luxurious oasis in arid surroundings.",
    //   img: "https://example.com/desert-villa.jpg",
    //   price: 280,
    //   location: "Scottsdale",
    //   country: "United States",
    // },
    // {
    //   title: "Tropical Rainforest Retreat",
    //   des: "Immerse yourself in the vibrant ecosystem of a tropical rainforest with a stay in this eco-friendly retreat.",
    //   img: "https://example.com/rainforest-retreat.jpg",
    //   price: 200,
    //   location: "Amazon Rainforest",
    //   country: "Brazil",
    // },
    // {
    //   title: "Classic European Chateau",
    //   des: "Live like royalty in this classic European chateau, surrounded by manicured gardens and historic charm.",
    //   img: "https://example.com/european-chateau.jpg",
    //   price: 500,
    //   location: "Loire Valley",
    //   country: "France",
    // },
    // {
    //   title: "Secluded Desert Oasis",
    //   des: "Discover a secluded oasis in the desert, where tranquility meets the rugged beauty of the arid landscape.",
    //   img: "https://example.com/desert-oasis.jpg",
    //   price: 220,
    //   location: "Joshua Tree",
    //   country: "United States",
    // },
    // {
    //   title: "Historic Asian Pagoda",
    //   des: "Step into the past with a stay in this historic Asian pagoda, surrounded by serene gardens and cultural heritage.",
    //   img: "https://example.com/asian-pagoda.jpg",
    //   price: 180,
    //   location: "Kyoto",
    //   country: "Japan",
    // },
    // {
    //   title: "Charming Coastal Lighthouse",
    //   des: "Experience coastal living in a charming lighthouse, offering panoramic views of the sea and coastline.",
    //   img: "https://example.com/coastal-lighthouse.jpg",
    //   price: 250,
    //   location: "Nova Scotia",
    //   country: "Canada",
    // },
    // {
    //   title: "Eco-Friendly Beach Bungalow",
    //   des: "Stay in an eco-friendly beach bungalow, where sustainability meets seaside relaxation.",
    //   img: "https://example.com/eco-beach-bungalow.jpg",
    //   price: 150,
    //   location: "Costa Rica",
    //   country: "Costa Rica",
    // },
    // {
    //   title: "Zen Mountain Retreat",
    //   des: "Escape to a zen mountain retreat, where tranquility and natural beauty come together for a rejuvenating experience.",
    //   img: "https://example.com/zen-mountain-retreat.jpg",
    //   price: 180,
    //   location: "Himalayas",
    //   country: "India",
    // },
    // {
    //   title: "Italian Riviera Villa",
    //   des: "Indulge in the glamour of the Italian Riviera with a stay in this villa, offering stunning views of the Mediterranean.",
    //   img: "https://example.com/italian-riviera-villa.jpg",
    //   price: 300,
    //   location: "Portofino",
    //   country: "Italy",
    // },
    // {
    //   title: "Mountain Safari Tent",
    //   des: "Embark on a mountain safari adventure with a stay in this tent, providing a comfortable base for exploration.",
    //   img: "https://example.com/mountain-safari-tent.jpg",
    //   price: 280,
    //   location: "Himalayas",
    //   country: "Nepal",
    // },
    // {
    //   title: "Chic Parisian Apartment",
    //   des: "Live the Parisian lifestyle in this chic apartment, located in the heart of the city's most fashionable district.",
    //   img: "https://example.com/parisian-apartment.jpg",
    //   price: 220,
    //   location: "Paris",
    //   country: "France",
    // },
    // {
    //   title: "Historic Irish Castle",
    //   des: "Step into history with a stay in this beautifully preserved Irish castle, complete with turrets and ancient charm.",
    //   img: "https://example.com/irish-castle.jpg",
    //   price: 400,
    //   location: "County Clare",
    //   country: "Ireland",
    // },
    // {
    //   title: "Modern Mountain View Home",
    //   des: "Enjoy modern comfort with a stunning mountain view in this stylish home, perfect for a relaxing getaway.",
    //   img: "https://example.com/mountain-view-home.jpg",
    //   price: 180,
    //   location: "Whistler",
    //   country: "Canada",
    // },
    // {
    //   title: "Beachfront Treehouse Villa",
    //   des: "Experience the unique combination of beachfront luxury and treetop seclusion in this villa.",
    //   img: "https://example.com/beachfront-treehouse.jpg",
    //   price: 300,
    //   location: "Phuket",
    //   country: "Thailand",
    // },
    // {
    //   title: "Historic Middle Eastern Riad",
    //   des: "Immerse yourself in the rich culture of the Middle East with a stay in this historic riad, featuring intricate architecture.",
    //   img: "https://example.com/middle-eastern-riad.jpg",
    //   price: 250,
    //   location: "Marrakech",
    //   country: "Morocco",
    // },
    // {
    //   title: "Ski-In-Ski-Out Chalet",
    //   des: "Hit the slopes with ease in this ski-in-ski-out chalet, offering convenience and stunning alpine views.",
    //   img: "https://example.com/ski-chalet.jpg",
    //   price: 280,
    //   location: "Chamonix",
    //   country: "France",
    // },
    // {
    //   title: "Caribbean Island Retreat",
    //   des: "Escape to a Caribbean island retreat, where white sandy beaches and turquoise waters await your arrival.",
    //   img: "https://example.com/caribbean-island-retreat.jpg",
    //   price: 320,
    //   location: "Saint Lucia",
    //   country: "Saint Lucia",
    // },
    // {
    //   title: "Modern City Skyline Apartment",
    //   des: "Enjoy breathtaking city skyline views from this modern apartment located in the heart of the metropolis.",
    //   img: "https://example.com/city-skyline-apartment.jpg",
    //   price: 200,
    //   location: "Hong Kong",
    //   country: "China",
    // },
    // {
    //   title: "African Savannah Lodge",
    //   des: "Experience the wonders of the African savannah with a stay in this lodge, offering a front-row seat to wildlife.",
    //   img: "https://example.com/savannah-lodge.jpg",
    //   price: 300,
    //   location: "Kruger National Park",
    //   country: "South Africa",
    // },
    // {
    //   title: "Riverside Treehouse Escape",
    //   des: "Escape to nature with a stay in this riverside treehouse, providing a cozy and secluded retreat.",
    //   img: "https://example.com/riverside-treehouse.jpg",
    //   price: 180,
    //   location: "Blue Ridge Mountains",
    //   country: "United States",
    // },
    // {
    //   title: "Historic Colonial Manor",
    //   des: "Step back in time with a stay in this historic colonial manor, surrounded by manicured gardens and period furnishings.",
    //   img: "https://example.com/colonial-manor.jpg",
    //   price: 350,
    //   location: "Williamsburg",
    //   country: "United States",
    // },
    // {
    //   title: "Tropical Oasis Villa",
    //   des: "Indulge in the ultimate tropical escape with this oasis villa, surrounded by lush greenery and a private pool.",
    //   img: "https://example.com/tropical-oasis-villa.jpg",
    //   price: 400,
    //   location: "Bali",
    //   country: "Indonesia",
    // },
    // {
    //   title: "Classic American Farmhouse",
    //   des: "Experience the charm of a classic American farmhouse, complete with a red barn and pastoral views.",
    //   img: "https://example.com/american-farmhouse.jpg",
    //   price: 150,
    //   location: "Vermont",
    //   country: "United States",
    // },
    // {
    //   title: "Mediterranean Seaside Retreat",
    //   des: "Escape to the Mediterranean with this seaside retreat, offering stunning views and coastal serenity.",
    //   img: "https://example.com/mediterranean-retreat.jpg",
    //   price: 280,
    //   location: "Amalfi Coast",
    //   country: "Italy",
    // },
    // {
    //   title: "Ski Resort Chalet",
    //   des: "Hit the slopes with ease and return to this cozy ski resort chalet, featuring a fireplace and mountain views.",
    //   img: "https://example.com/ski-resort-chalet.jpg",
    //   price: 250,
    //   location: "Park City",
    //   country: "United States",
    // },
    // {
    //   title: "African Safari Lodge",
    //   des: "Immerse yourself in the African wilderness with a stay in this safari lodge, surrounded by nature and wildlife.",
    //   img: "https://example.com/african-safari-lodge.jpg",
    //   price: 300,
    //   location: "Serengeti",
    //   country: "Tanzania",
    // },
    // {
    //   title: "Historic Spanish Hacienda",
    //   des: "Step into the past with a stay in this historic Spanish hacienda, featuring traditional architecture and elegant courtyards.",
    //   img: "https://example.com/spanish-hacienda.jpg",
    //   price: 400,
    //   location: "Andalusia",
    //   country: "Spain",
    // },
    // {
    //   title: "Coastal Cliffside Villa",
    //   des: "Perched on a coastal cliff, this villa offers breathtaking views of the sea and a luxurious escape.",
    //   img: "https://example.com/coastal-cliffside-villa.jpg",
    //   price: 350,
    //   location: "Amalfi Coast",
    //   country: "Italy",
    // },
    // {
    //   title: "Scandinavian Lakeside Cabin",
    //   des: "Experience the simplicity of Scandinavian design in this lakeside cabin, surrounded by nature's tranquility.",
    //   img: "https://example.com/scandinavian-cabin.jpg",
    //   price: 180,
    //   location: "Norway",
    //   country: "Norway",
    // },
    // {
    //   title: "Island Paradise Resort",
    //   des: "Indulge in luxury at this island paradise resort, featuring overwater bungalows and pristine beaches.",
    //   img: "https://example.com/island-paradise-resort.jpg",
    //   price: 500,
    //   location: "Bora Bora",
    //   country: "French Polynesia",
    // },
    // {
    //   title: "Historic Dutch Windmill",
    //   des: "Step into the past with a stay in this historic Dutch windmill, offering unique accommodations and countryside views.",
    //   img: "https://example.com/dutch-windmill.jpg",
    //   price: 200,
    //   location: "Amsterdam",
    //   country: "Netherlands",
    // },
    // {
    //   title: "Lakeside Treehouse Retreat",
    //   des: "Escape to a lakeside treehouse retreat, where you can unwind amidst the beauty of nature and serene waters.",
    //   img: "https://example.com/lakeside-treehouse-retreat.jpg",
    //   price: 250,
    //   location: "Lake District",
    //   country: "United Kingdom",
    // },
    // {
    //   title: "Modern Desert Oasis",
    //   des: "Experience modern luxury in the desert with this oasis retreat, offering a private pool and stunning views.",
    //   img: "https://example.com/modern-desert-oasis.jpg",
    //   price: 300,
    //   location: "Palm Springs",
    //   country: "United States",
    // },
    // {
    //   title: "Secluded Forest Cabin",
    //   des: "Find seclusion in this forest cabin, surrounded by towering trees and the sounds of nature.",
    //   img: "https://example.com/forest-cabin.jpg",
    //   price: 160,
    //   location: "Adirondacks",
    //   country: "United States",
    // },
    // {
    //   title: "Mountain View Treehouse",
    //   des: "Experience the magic of a mountain view treehouse, where you can reconnect with nature high above the ground.",
    //   img: "https://example.com/mountain-view-treehouse.jpg",
    //   price: 200,
    //   location: "Appalachian Mountains",
    //   country: "United States",
    // },
    // {
    //   title: "Urban Industrial Loft",
    //   des: "Live in style with this urban industrial loft, featuring exposed brick walls and contemporary design.",
    //   img: "https://example.com/industrial-loft.jpg",
    //   price: 180,
    //   location: "Brooklyn",
    //   country: "United States",
    // },
    // {
    //   title: "Rustic Lakeside Lodge",
    //   des: "Cozy up in this rustic lakeside lodge, offering a warm retreat with beautiful views of the water.",
    //   img: "https://example.com/lakeside-lodge.jpg",
    //   price: 150,
    //   location: "Lake Placid",
    //   country: "United States",
    // },
    // {
    //   title: "Private Beachfront Mansion",
    //   des: "Indulge in luxury at this private beachfront mansion, where exclusivity meets the serenity of the ocean.",
    //   img: "https://example.com/beachfront-mansion.jpg",
    //   price: 800,
    //   location: "Hamptons",
    //   country: "United States",
    // },
    // {
    //   title: "Historic Russian Dacha",
    //   des: "Step into Russian history with a stay in this historic dacha, surrounded by gardens and traditional architecture.",
    //   img: "https://example.com/russian-dacha.jpg",
    //   price: 250,
    //   location: "Moscow",
    //   country: "Russia",
    // },
    // {
    //   title: "Swiss Mountain Hut",
    //   des: "Experience the charm of a Swiss mountain hut, where alpine views and cozy interiors create a perfect retreat.",
    //   img: "https://example.com/swiss-mountain-hut.jpg",
    //   price: 180,
    //   location: "Swiss Alps",
    //   country: "Switzerland",
    // },
    // {
    //   title: "Bohemian Beach Yurt",
    //   des: "Embrace bohemian vibes in this beachfront yurt, offering a unique and laid-back coastal experience.",
    //   img: "https://example.com/beach-yurt.jpg",
    //   price: 120,
    //   location: "Byron Bay",
    //   country: "Australia",
    // },
    // {
    //   title: "Majestic Mountain View Chalet",
    //   des: "Enjoy majestic mountain views from this cozy chalet, where outdoor adventures and relaxation await.",
    //   img: "https://example.com/mountain-view-chalet.jpg",
    //   price: 220,
    //   location: "Rocky Mountains",
    //   country: "United States",
    // },
    // {
    //   title: "Eco-Friendly Mountain Lodge",
    //   des: "Stay in harmony with nature at this eco-friendly mountain lodge, surrounded by pristine wilderness.",
    //   img: "https://example.com/mountain-lodge.jpg",
    //   price: 200,
    //   location: "Patagonia",
    //   country: "Argentina",
    // },
    // {
    //   title: "Sunny Spanish Villa",
    //   des: "Bask in the Spanish sun at this sunny villa, offering a private pool and beautiful Mediterranean views.",
    //   img: "https://example.com/spanish-villa.jpg",
    //   price: 300,
    //   location: "Cost
  